name: wyca
description: clean car app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route:
  flutter_screenutil: ^5.5.3+1

  smooth_page_indicator: ^1.0.0+2
  bloc: ^8.0.3
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  socket_io_client: ^2.0.0-beta.2

  google_maps_flutter: ^2.1.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  pin_code_fields: ^7.4.0
  lottie: ^2.3.0
  flutter_svg: ^2.0.4
  simple_animations:
  freezed_annotation:
  flutter_secure_storage:
  dartz:
  formz: ^0.4.1
  carousel_slider: ^4.1.1
  grouped_list:
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  video_player: ^2.4.2
  dio: ^4.0.6
  firebase_core: ^2.8.0
  firebase_messaging:
  fluttertoast:
  get_it: ^7.2.0
  overlay_support: ^2.0.1
  image_picker: ^0.8.5+3
  flutter_local_notifications: ^14.0.0-dev.2
  awesome_notifications:
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.7
  flutter_webview_plugin: ^0.4.0
  badges: ^3.0.3
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.3.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  loading_indicator: ^3.1.0

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_launcher_icons:
  auto_route_generator:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_native_splash: ^2.2.7
  very_good_analysis: ^4.0.0+1
  google_fonts: ^4.0.3
  build_runner:
  flutter_gen_runner:
  # pubspec.yaml
# pubspec.yaml
# ...
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
flutter_gen:
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  # flutter font family
  # Path: assets/fonts/
  assets:
    - assets/lottie/
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/drawer_icons/
    - assets/icons/

  fonts:
    - family: "Lobster"
      fonts:
        - asset: "assets/fonts/Lobster-Regular.ttf"

    - family: "Cairo"
      fonts:
        - asset: "assets/fonts/Cairo-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Cairo-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Cairo-ExtraLight.ttf"
          weight: 200
        - asset: "assets/fonts/Cairo-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Cairo-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Cairo-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Cairo-SemiBold.ttf"
          weight: 600
