// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo_sHOYlqf9n-IUWdnYYp1wABATqM8uwE',
    appId: '1:449531267886:web:f3231cd28689c2b3cdc8bf',
    messagingSenderId: '449531267886',
    projectId: 'wyca-4b445',
    authDomain: 'wyca-4b445.firebaseapp.com',
    storageBucket: 'wyca-4b445.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQVTDYOCH6_i6PFzIhBCN-pBj_5mCsxt8',
    appId: '1:449531267886:android:43de7cc423242189cdc8bf',
    messagingSenderId: '449531267886',
    projectId: 'wyca-4b445',
    storageBucket: 'wyca-4b445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTUWleW-J15eZsTFKX460dj0sUxob14YM',
    appId: '1:449531267886:ios:f210cef7de9f9541cdc8bf',
    messagingSenderId: '449531267886',
    projectId: 'wyca-4b445',
    storageBucket: 'wyca-4b445.appspot.com',
    iosClientId:
        '449531267886-970l647i46jpb7n0cbq1bv006de0m382.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.wyca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTUWleW-J15eZsTFKX460dj0sUxob14YM',
    appId: '1:449531267886:ios:f210cef7de9f9541cdc8bf',
    messagingSenderId: '449531267886',
    projectId: 'wyca-4b445',
    storageBucket: 'wyca-4b445.appspot.com',
    iosClientId:
        '449531267886-970l647i46jpb7n0cbq1bv006de0m382.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.wyca',
  );
}
